name: Auto Update Rules

on:
  push:
    paths:
      - 'custom-rules/self-use-source.txt'
      - 'update_self_use_rules.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run self use generator
        run: python update_self_use_rules.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add custom-rules/self-use-rules.list custom-rules/self-use-rules.lsr custom-rules/self-use-rules.yaml
          git commit -m "chore: update self use rules" || exit 0
          git push
